### ISSUE TITLE
Review for Team 108 (The Mamba)

### ISSUE THREAD

**Issue by ebeagusamuel** [ozovalihasan/private_events#1]
- Nice work implementing the manual sign-up, and login.
- You can try to improve the UI of the project.
- You can try to study more and understand how associations works in rails active record.

**Comment by ozovalihasan** [comment]
Thanks, @ebeagusamuel, for your feedback. We added some small styles to improve the UI of the project, but we are planning to enhance more. More associations are fixed, and they are working as expected. If you have another suggestion, please let us know it.
