### ISSUE TITLE
Review for Team 108 (The mambas)

### ISSUE THREAD

**Issue by ebeagusamuel** [ozovalihasan/private_events#3]
- The project is looking nice
- You can try add integration tests.
- If you like you can try to add a feature where a user can apply to attend an event as long as the event is not private.

**Comment by ozovalihasan** [comment]
Thanks, @ebeagusamuel, for your suggestion. We implemented one of your suggestions. But, we are not planning to implement your second suggestion because we assumed all events are private events for this project. If you have another opinion, let us know it.
