### ISSUE TITLE
Code review for team 108(The Mambas)

### ISSUE THREAD

**Issue by ebeagusamuel** [ozovalihasan/private_events#5]
#### There are a few things you can fix.
- A user shouldn't be able to signup without at least providing a username. Therefore you should be validating the presence of username to be true before signing up a user.
- Once a user has been invited to a particular event, you shouldn't be able to invite that same user for that same event again.

**Comment by ozovalihasan** [comment]
Thanks, @ebeagusamuel, for your feedback. We implemented your suggestions. If you have other feedback, let us know it.
